// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCbqagkre_pN0vV8RXZgbMR9EErgW4ZPs',
    appId: '1:802563164625:web:24f1c35bad0a7f0071b8f0',
    messagingSenderId: '802563164625',
    projectId: 'login-76c06',
    authDomain: 'login-76c06.firebaseapp.com',
    storageBucket: 'login-76c06.appspot.com',
    measurementId: 'G-HP5KXQ9GZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO8gywjvLEkSjtc1GthEprzfwBBSVC27A',
    appId: '1:802563164625:android:39abb0b5e004d3da71b8f0',
    messagingSenderId: '802563164625',
    projectId: 'login-76c06',
    storageBucket: 'login-76c06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7fZvrkhQue0UQN3iEz-9crzSxlBpdR28',
    appId: '1:802563164625:ios:606e0b48c869612371b8f0',
    messagingSenderId: '802563164625',
    projectId: 'login-76c06',
    storageBucket: 'login-76c06.appspot.com',
    iosClientId: '802563164625-64ud242pms3ijor09788poq7dbacs70a.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGanamax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7fZvrkhQue0UQN3iEz-9crzSxlBpdR28',
    appId: '1:802563164625:ios:606e0b48c869612371b8f0',
    messagingSenderId: '802563164625',
    projectId: 'login-76c06',
    storageBucket: 'login-76c06.appspot.com',
    iosClientId: '802563164625-64ud242pms3ijor09788poq7dbacs70a.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGanamax',
  );
}
